name: List Repo Env

on:
  workflow_dispatch:
    inputs:
      age_key:
        description: 'Enter a public age key'
        required: true
        type: string

jobs:
  base:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install age
        run: |
          sudo apt-get update
          sudo apt-get install -y age
      - env: ${{ secrets }}
        run: |
          echo '${{ toJSON(vars) }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
          echo ${{env.DEV_ENV_SECRET}}
          echo ${{env.DEV_ENV_VARIABLE}}
          env | age -a -e -r "${{ inputs.age_key }}" > env.age
      - uses: actions/upload-artifact@v4.6.1
        with:
          name: env.age
          path: env.age
          retention-days: 1
  
  development:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Install age
        run: |
          sudo apt-get update
          sudo apt-get install -y age
      - env: ${{ secrets }}
        run: |
          echo '${{ toJSON(vars) }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
          echo ${{env.DEV_ENV_SECRET}}
          echo ${{env.DEV_ENV_VARIABLE}}
          env | age -a -e -r "${{ inputs.age_key }}" > env.age
      - uses: actions/upload-artifact@v4.6.1
        with:
          name: env.age
          path: env.age
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Install age
        run: |
          sudo apt-get update
          sudo apt-get install -y age
      - env: ${{ secrets }}
        run: |
          echo '${{ toJSON(vars) }}' | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
          echo ${{env.DEV_ENV_SECRET}}
          echo ${{env.DEV_ENV_VARIABLE}}
          env | age -a -e -r "${{ inputs.age_key }}" > env.age
      - uses: actions/upload-artifact@v4.6.1
        with:
          name: env.age
          path: env.age
          retention-days: 1
