name: "GHA summary example"

on:
  workflow_dispatch:

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: Adding markdown
        run: echo '### Hello world! ' >> $GITHUB_STEP_SUMMARY
