name: teste input
on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  teste:
    name: teste
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo env=${{ inputs.env && inputs.env || 'prod' }}!
